name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Update
      run: sudo apt-get update
    - name: Install dev packages
      run: sudo apt-get install libsqlite3-dev musl-tools
    - name: Install latest rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-unknown-linux-musl
        default: true
        override: true
    - name: Run tests
      run: cargo test --verbose
    - name: Build
      run: cargo build --verbose --release --target x86_64-unknown-linux-musl && cp target/x86_64-unknown-linux-musl/release/rdftab rdftab-x86_64-unknown-linux-musl
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: rdftab-x86_64-unknown-linux-musl
        path: rdftab-x86_64-unknown-linux-musl
