name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Update
      run: sudo apt-get update
    - name: Install sqlite3 dev files
      run: sudo apt-get install libsqlite3-dev
    - name: Build
      run: cargo build --verbose --release && cp target/release/rdftab rdftab-x86_64-unknown-linux-gnu
    - name: Run tests
      run: cargo test --verbose
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        path: rdftab-x86_64-unknown-linux-gnu
